#connector_name: ""
#connector_module_path: "example_connectors/docker_example.py"

#connector_name: ""
#connector_module_path: "example_connectors/income_full_docker.py"
#
connector_name: ""
connector_module_path: "example_connectors/income_no_docker.py"

#connector_name: ""
#connector_module_path: "example_connectors/cifar_no_docker.py"


