front_end: "fastapi"
storage_path: "./SM_storage/"
staging_path: "./Staging_storage/"
log_in_memory: False
log_path: "ds_log.pkl"
wal_path: "wal.pkl"
check_point_freq: 10
table_paths: ["users.pkl", "dataelements.pkl", "policies.pkl", "stagings.pkl", "provenances.pkl"]
mount_path: "./SM_storage_mount/"
database_url: "sqlite:///./data_station.db"
trust_mode: "full_trust"
in_development_mode: True
