front_end: "fastapi"
storage_path: "./SM_storage/"
log_in_memory: False
log_path: "ds_log.pkl"
wal_path: "wal.pkl"
check_point_freq: 999999
table_paths: ["users.pkl", "dataelements.pkl", "policies.pkl"]
mount_path: "./SM_storage_mount/"
database_url: "sqlite://"
trust_mode: "no_trust"
